version: '3.7'

services:
  web:
    build: .
    env_file:
      - config/.env.development

    command: python /app/bookmarks/manage.py runserver 0.0.0.0:8000
    
    volumes:
      - .:/app
    ports:
      - 8000:8000
  db:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis
    env_file:
      - .env 
    ports:
      - 6379:6379
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - ./redis_data:/data
    
    

volumes:
  postgres_data:
  redis_data: